export const FETCH_PARKS_START = 'FETCH_PARKS_START';
export const FETCH_PARKS_SUCCESS = 'FETCH_PARKS_SUCCESS';
export const FETCH_PARKS_FAIL = 'FETCH_PARKS_FAIL';


export const FETCH_PARK_START = 'FETCH_PARK_START';
export const FETCH_PARK_SUCCESS = 'FETCH_PARK_SUCCESS';
export const FETCH_PARK_FAIL = 'FETCH_PARK_FAIL';

export const UPDATE_PARK_FILTER = 'UPDATE_PARK_FILTER';

export const FETCH_DOGS_START = 'FETCH_DOGS_START';
export const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
export const FETCH_DOGS_FAIL = 'FETCH_DOGS_FAIL';


export const FETCH_DOG_START = 'FETCH_DOG_START';
export const FETCH_DOG_SUCCESS = 'FETCH_DOG_SUCCESS';
export const FETCH_DOG_FAIL = 'FETCH_DOG_FAIL';

export const FETCH_DOG_ATTRIBUTE_START = 'FETCH_DOG_ATTRIBUTE_START';
export const FETCH_DOG_ATTRIBUTE_SUCCESS = 'FETCH_DOG_ATTRIBUTE_SUCCESS';
export const FETCH_DOG_ATTRIBUTE_FAIL = 'FETCH_DOG_ATTRIBUTE_FAIL';

export const UPDATE_DOG_FILTER = 'UPDATE_DOG_FILTER';