export const FETCH_PARKS_START = 'FETCH_PARKS_START';
export const FETCH_PARKS_SUCCESS = 'FETCH_PARKS_SUCCESS';
export const FETCH_PARKS_FAIL = 'FETCH_PARKS_FAIL';


export const FETCH_PARK_START = 'FETCH_PARK_START';
export const FETCH_PARK_SUCCESS = 'FETCH_PARK_SUCCESS';
export const FETCH_PARK_FAIL = 'FETCH_PARK_FAIL';