export const FETCH_PARKS_START = 'FETCH_PARKS_START';
export const FETCH_PARKS_SUCCESS = 'FETCH_PARKS_SUCCESS';
export const FETCH_PARKS_FAIL = 'FETCH_PARKS_FAIL';

export const FETCH_PARK_START = 'FETCH_PARK_START';
export const FETCH_PARK_SUCCESS = 'FETCH_PARK_SUCCESS';
export const FETCH_PARK_FAIL = 'FETCH_PARK_FAIL';

export const UPDATE_PARK_FILTER = 'UPDATE_PARK_FILTER';
export const RESET_PARK_FILTER = 'RESET_PARK_FILTER';

export const FETCH_DOGS_START = 'FETCH_DOGS_START';
export const FETCH_DOGS_SUCCESS = 'FETCH_DOGS_SUCCESS';
export const FETCH_DOGS_FAIL = 'FETCH_DOGS_FAIL';

export const FETCH_DOG_START = 'FETCH_DOG_START';
export const FETCH_DOG_SUCCESS = 'FETCH_DOG_SUCCESS';
export const FETCH_DOG_FAIL = 'FETCH_DOG_FAIL';

export const FETCH_DOG_ATTRIBUTE_START = 'FETCH_DOG_ATTRIBUTE_START';
export const FETCH_DOG_ATTRIBUTE_SUCCESS = 'FETCH_DOG_ATTRIBUTE_SUCCESS';
export const FETCH_DOG_ATTRIBUTE_FAIL = 'FETCH_DOG_ATTRIBUTE_FAIL';

export const UPDATE_DOG_FILTER = 'UPDATE_DOG_FILTER';
export const RESET_DOG_FILTER = 'RESET_DOG_FILTER';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const UPDATE_USER_FILTER = 'UPDATE_USER_FILTER';
export const RESET_USER_FILTER = 'RESET_USER_FILTER';

export const UPDATE_AUTHENTICATING_STATE = 'UPDATE_AUTHENTICATING_STATE';
export const UPDATE_SIGN_UP_STATE = 'UPDATE_SIGN_UP_STATE';
export const HANDLE_USER_LOGIN = 'HANDLE_USER_LOGIN'

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const USER_SIGN_UP_START = 'USER_SIGN_UP_START';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAIL = 'USER_SIGN_UP_FAIL';

export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';

export const FETCH_NEIGHBORHOODS_START = 'FETCH_NEIGHBORHOODS_START';
export const FETCH_NEIGHBORHOODS_SUCCESS = 'FETCH_NEIGHBORHOODS_SUCCESS';
export const FETCH_NEIGHBORHOODS_FAIL = 'FETCH_NEIGHBORHOODS_FAIL';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const REMOVE_SELECTED_USER = 'REMOVE_SELECTED_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
